services:
  fronted:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3000:80"
    environment:
      - VITE_API_PATH=http://32.192.255.196:5000  # 👈 Apna IP daalo

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
          condition: service_healthy
    environment:
      - MONGODB_URI=mongodb://mongo:27017/wanderlust
      - PORT=5000
    restart: always

  mongo:
    image: mongo:6
    restart: always
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    healthcheck:
    test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
    interval: 10s
    timeout: 5s
    retries: 5

volumes:
  mongo_data: